### ISSUE TITLE
login screen look and feel

### ISSUE THREAD

**Issue by ghost** [loveall-serveall/walk-with-values#2]
1. make text boxes smaller in width
2. remove space between label and textbox
3. add text on the top of the labels
   "If this is your first time, please register here"
   or go the register link at the bottom of the page.

"register" text above should be a hyperlink to a register page.

**Comment by lakshman537** [comment]
"register" text above should be a hyperlink to a register page.

**Comment by saisura** [comment]
Done! please verify and close the bug

**Comment by psura** [comment]
Verified. Looks good.

**Comment by psura** [comment]
When session expires, user is redirected to login page but the UI has some formatting issues with the new content/links that we added as part of the this bug.
![login-page-formatting-issue-when-session-expires](https://cloud.githubusercontent.com/assets/2641359/7663744/1bfd3b40-fb25-11e4-894b-ee24ab8394d0.png)

**Comment by ghost** [comment]
and can you just call it "First time ? Register here"

**Comment by psura** [comment]
fixed.
